services:
  - type: web
    name: solar-calculator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python solar_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 10000
